std = "lua51"

globals = {
    "ADD_ON_MANAGER",
    "AddOnManager",
    "BOTTOMLEFT",
    "CALLBACK_MANAGER",
    "CENTER",
    "CT_CONTROL",
    "CT_LABEL",
    "EVENT_ADD_ON_LOADED",
    "EVENT_MANAGER",
    "EZOCore",
    "GetControl",
    "GetCVar",
    "GetString",
    "GuiRoot",
    "KEYBOARD_OPTIONS",
    "LAMCreateControl",
    "LibAddonMenu2",
    "LibDebugLogger",
    "ReloadUI",
    "SCENE_MANAGER",
    "SCENE_SHOWN",
    "SI_GAME_MENU_SETTINGS",
    "TEXT_WRAP_MODE_ELLIPSIS",
    "TOPLEFT",
    "WINDOW_MANAGER",
    "ZO_FadeSceneFragment",
    "ZO_GameMenu_AddSettingPanel",
    "ZO_GameMenu_InGame",
    "ZO_ScrollContainer",
    "ZO_SimpleSceneFragment",
}
